-- ============================================================
-- supabase_schema.sql
-- Auto-generated by gen_schema.py for PSX → Supabase migration
-- DO NOT EXECUTE until reviewed
-- ============================================================

-- Table: agent_chat_log (39 rows)
CREATE TABLE IF NOT EXISTS "agent_chat_log" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "session_id" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "symbols_mentioned" TEXT,
    "emotions" TEXT,
    "question_type" TEXT,
    "market_regime" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: agent_learning_log (19 rows)
CREATE TABLE IF NOT EXISTS "agent_learning_log" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "run_date" DATE NOT NULL  -- detected as DATE from samples,
    "run_type" TEXT NOT NULL DEFAULT 'daily',
    "opportunities_generated" INTEGER DEFAULT 0,
    "patterns_updated" INTEGER DEFAULT 0,
    "market_regime" TEXT,
    "key_observations" TEXT,
    "model_used" TEXT,
    "tokens_used" INTEGER,
    "run_duration_sec" NUMERIC(18,6)  -- price/financial — exact precision,
    "error_log" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: agent_memory (7 rows)
CREATE TABLE IF NOT EXISTS "agent_memory" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "ts" TIMESTAMP NOT NULL DEFAULT NOW(),
    "market_date" DATE NOT NULL  -- detected as DATE from samples,
    "trigger_type" TEXT NOT NULL,
    "regime" TEXT,
    "zeeshan_input" TEXT,
    "stance" TEXT,
    "response" TEXT NOT NULL,
    "flagged_setups" TEXT,
    "context_snapshot" TEXT,
    "model" TEXT,
    "prompt_tokens" INTEGER,
    "completion_tokens" INTEGER
);

-- Table: agent_opportunities (31 rows)
CREATE TABLE IF NOT EXISTS "agent_opportunities" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "run_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "direction" TEXT NOT NULL,
    "pattern_name" TEXT,
    "pattern_id" INTEGER,
    "confidence_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "entry_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6)  -- price/financial — exact precision,
    "target_1r" NUMERIC(18,6)  -- price/financial — exact precision,
    "target_2r" NUMERIC(18,6)  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "reasoning" TEXT NOT NULL,
    "sector" TEXT,
    "sector_momentum" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "outcome" TEXT,
    "actual_exit" NUMERIC(18,6)  -- price/financial — exact precision,
    "exit_date" DATE  -- detected as DATE from samples,
    "actual_pl_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "notes" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples,
    "kse100_entry_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "kse100_exit_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "kse100_return_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "alpha_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "regime_at_creation" TEXT,
    "universe_stage3_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "suppressed_reason" TEXT,
    "suppressed_date" TEXT  -- detected as TEXT from samples
);

-- Table: agent_patterns (6 rows)
CREATE TABLE IF NOT EXISTS "agent_patterns" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "pattern_name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "conditions" TEXT NOT NULL,
    "first_seen" TEXT NOT NULL,
    "last_updated" DATE NOT NULL  -- detected as DATE from samples,
    "signal_count" INTEGER NOT NULL DEFAULT 0,
    "win_count" INTEGER NOT NULL DEFAULT 0,
    "loss_count" INTEGER NOT NULL DEFAULT 0,
    "win_rate_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "avg_pl_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "profit_factor" NUMERIC(18,6)  -- price/financial — exact precision,
    "confidence" TEXT NOT NULL DEFAULT 'Low',
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE  -- sampled — only 0/1 values,
    "raw_json" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: agent_reference_breakouts (3 rows)
CREATE TABLE IF NOT EXISTS "agent_reference_breakouts" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "symbol" TEXT NOT NULL,
    "breakout_date" DATE NOT NULL  -- detected as DATE from samples,
    "pre_consol_days" INTEGER,
    "pre_range_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "pre_rs_vs_kse" DOUBLE PRECISION,
    "pre_ma21_dist_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "pre_ma50_dist_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "pre_ma200_dist_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "pre_vol_ratio" NUMERIC(18,6)  -- price/financial — exact precision,
    "bo_candle_range_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "post_gain_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "post_days_to_peak" INTEGER,
    "analysis_text" TEXT,
    "notes" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples,
    "direction" TEXT NOT NULL DEFAULT 'LONG'
);

-- Table: agent_reports (13 rows)
CREATE TABLE IF NOT EXISTS "agent_reports" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "run_date" DATE NOT NULL  -- detected as DATE from samples,
    "report_type" TEXT NOT NULL,
    "market_regime" TEXT,
    "breadth_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "narrative" TEXT NOT NULL,
    "raw_json" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: agent_trader_profile (1 rows)
CREATE TABLE IF NOT EXISTS "agent_trader_profile" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "week_date" DATE NOT NULL  -- detected as DATE from samples,
    "profile_text" TEXT NOT NULL,
    "key_biases" TEXT,
    "temptation_stocks" TEXT,
    "emotion_counts" TEXT,
    "regime_behavior" TEXT,
    "guardrail_rules" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: backtest_setups (4,344 rows)
CREATE TABLE IF NOT EXISTS "backtest_setups" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "as_of_date" DATE NOT NULL  -- detected as DATE from samples,
    "direction" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "sector_momentum" TEXT,
    "sector_rank" INTEGER,
    "breadth_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "stock_perf_30d" DOUBLE PRECISION,
    "stock_perf_60d" DOUBLE PRECISION,
    "stock_perf_10d" DOUBLE PRECISION,
    "latest_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "support_level" DOUBLE PRECISION,
    "resistance_level" DOUBLE PRECISION,
    "entry_price" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "target_1r" NUMERIC(18,6)  -- price/financial — exact precision,
    "target_2r" NUMERIC(18,6)  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "atr_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "range_width_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "range_window" INTEGER,
    "quality_score" INTEGER,
    "avg_vol_10d" DOUBLE PRECISION,
    "entry_triggered" INTEGER DEFAULT 0,
    "trigger_date" DATE  -- detected as DATE from samples,
    "outcome" TEXT,
    "outcome_date" DATE  -- detected as DATE from samples,
    "outcome_days" INTEGER,
    "realized_r" DOUBLE PRECISION
);

-- Table: corporate_action_suspects (4 rows)
CREATE TABLE IF NOT EXISTS "corporate_action_suspects" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "symbol" TEXT NOT NULL,
    "suspect_date" DATE NOT NULL  -- detected as DATE from samples,
    "close_before" NUMERIC(18,6)  -- price/financial — exact precision,
    "close_after" NUMERIC(18,6)  -- price/financial — exact precision,
    "drop_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "likely_category" TEXT,
    "status" TEXT DEFAULT 'PENDING',
    "confirmed_action" TEXT,
    "adjustment_factor" NUMERIC(18,6)  -- price/financial — exact precision,
    "confirmed_at" TIMESTAMP  -- detected as TIMESTAMP from samples,
    "notes" TEXT
);

-- Table: financial_snapshots (0 rows)
CREATE TABLE IF NOT EXISTS "financial_snapshots" (
    "ticker" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "metric_name" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "value" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "category", "metric_name", "year")
);

-- Table: fs_analysis (1 rows)
CREATE TABLE IF NOT EXISTS "fs_analysis" (
    "ticker" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "executive_summary" TEXT,
    "growth_drivers" TEXT,
    "risks" TEXT,
    "red_flags" TEXT,
    "management_tone" TEXT,
    "outlook_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "key_metrics" TEXT,
    "capital_allocation" TEXT,
    "competitive_pos" TEXT,
    "analyzed_at" TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY ("ticker", "year")
);

-- Table: fs_line_items (580 rows)
CREATE TABLE IF NOT EXISTS "fs_line_items" (
    "ticker" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "key" TEXT NOT NULL,
    "value" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "year", "key")
);

-- Table: index_prices (16,528 rows)
CREATE TABLE IF NOT EXISTS "index_prices" (
    "symbol" TEXT NOT NULL,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "high" NUMERIC(18,6)  -- price/financial — exact precision,
    "low" NUMERIC(18,6)  -- price/financial — exact precision,
    "close" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "open" NUMERIC(18,6)  -- price/financial — exact precision,
    PRIMARY KEY ("symbol", "date")
);

-- Table: kse100_constituents (100 rows)
CREATE TABLE IF NOT EXISTS "kse100_constituents" (
    "symbol" TEXT,
    "company_name" TEXT NOT NULL,
    "sector" TEXT,
    PRIMARY KEY ("symbol")
);

-- Table: leaders_scan (82 rows)
CREATE TABLE IF NOT EXISTS "leaders_scan" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "scan_date" TEXT NOT NULL  -- unknown sqlite type — defaulted to TEXT,
    "setup_type" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "sector" TEXT,
    "sector_rank" INTEGER,
    "rs_rank" INTEGER,
    "sector_rs_rank" INTEGER,
    "rs_score_20" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_score_50" NUMERIC(18,6)  -- price/financial — exact precision,
    "rank_change" INTEGER,
    "base_tightness" NUMERIC(18,6)  -- price/financial — exact precision,
    "pivot_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "pivot_distance_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "avg_vol_10d" DOUBLE PRECISION,
    "vol_ratio_today" NUMERIC(18,6)  -- price/financial — exact precision,
    "entry_trigger" NUMERIC(18,6)  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6)  -- price/financial — exact precision,
    "sl_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_inflection" INTEGER,
    "sector_composite" DOUBLE PRECISION,
    "vol_rejection_flag" INTEGER,
    "nearest_overhead_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "raw_score" INTEGER,
    "penalty" INTEGER,
    "final_score" INTEGER,
    "flag" TEXT,
    "vol_contraction" DOUBLE PRECISION
);

-- Table: leaders_top_picks (6 rows)
CREATE TABLE IF NOT EXISTS "leaders_top_picks" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "scan_date" TEXT NOT NULL  -- unknown sqlite type — defaulted to TEXT,
    "setup_type" TEXT NOT NULL,
    "rank" INTEGER NOT NULL,
    "symbol" TEXT,
    "sector" TEXT,
    "sector_rank" INTEGER,
    "entry_trigger" NUMERIC(18,6)  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6)  -- price/financial — exact precision,
    "sl_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_ratio_today" NUMERIC(18,6)  -- price/financial — exact precision,
    "key_reason" TEXT,
    "flag" TEXT,
    "fwd_return_5d" NUMERIC(18,6)  -- price/financial — exact precision,
    "fwd_return_10d" NUMERIC(18,6)  -- price/financial — exact precision,
    "fwd_return_20d" NUMERIC(18,6)  -- price/financial — exact precision,
    "outcome_label" TEXT DEFAULT 'OPEN',
    "triggered" INTEGER,
    "trigger_date" TEXT  -- unknown sqlite type — defaulted to TEXT
);

-- Table: market_flows (1,032 rows)
CREATE TABLE IF NOT EXISTS "market_flows" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "flow_type" TEXT NOT NULL,
    "client_type" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "market_type" TEXT NOT NULL,
    "buy_volume" DOUBLE PRECISION,
    "buy_value" DOUBLE PRECISION,
    "sell_volume" DOUBLE PRECISION,
    "sell_value" DOUBLE PRECISION,
    "net_volume" DOUBLE PRECISION,
    "net_value" DOUBLE PRECISION,
    "usd_net" DOUBLE PRECISION
);

-- Table: market_regime (5,310 rows)
CREATE TABLE IF NOT EXISTS "market_regime" (
    "date" DATE  -- detected as DATE from samples,
    "close" NUMERIC(18,6)  -- price/financial — exact precision,
    "ema_20" DOUBLE PRECISION,
    "ema_50" DOUBLE PRECISION,
    "ema_200" DOUBLE PRECISION,
    "atr_20" NUMERIC(18,6)  -- price/financial — exact precision,
    "atr_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "return_20d" NUMERIC(18,6)  -- price/financial — exact precision,
    "regime" TEXT NOT NULL,
    "regime_days" INTEGER,
    "notes" TEXT,
    PRIMARY KEY ("date")
);

-- Table: mv_signals (7 rows)
CREATE TABLE IF NOT EXISTS "mv_signals" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "as_of_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "sector" TEXT,
    "signal_type" TEXT NOT NULL,
    "close" NUMERIC(18,6)  -- price/financial — exact precision,
    "ema20" DOUBLE PRECISION,
    "ema50" DOUBLE PRECISION,
    "ema200" DOUBLE PRECISION,
    "pivot_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "pivot_low" NUMERIC(18,6)  -- price/financial — exact precision,
    "bb_width" DOUBLE PRECISION,
    "high_200d" NUMERIC(18,6)  -- price/financial — exact precision,
    "atr_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_ratio" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_rating" DOUBLE PRECISION,
    "rs_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_avg20" DOUBLE PRECISION,
    "market_up" BOOLEAN  -- sampled — only 0/1 values,
    "is_dfc" INTEGER,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from TEXT,
    "rs_rank" INTEGER,
    "sector_rs_rank" INTEGER,
    "sector_breadth" NUMERIC(18,6)  -- price/financial — exact precision,
    "mkt_breadth" NUMERIC(18,6)  -- price/financial — exact precision
);

-- Table: portfolio_signals (2,424 rows)
CREATE TABLE IF NOT EXISTS "portfolio_signals" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "as_of_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "sector" TEXT,
    "latest_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "latest_date" DATE  -- detected as DATE from samples,
    "ma10w" DOUBLE PRECISION,
    "ma30w" DOUBLE PRECISION,
    "dist_from_30w_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "stage" INTEGER,
    "stage_label" TEXT,
    "rs_30d" DOUBLE PRECISION,
    "rs_10d" DOUBLE PRECISION,
    "rs_trend" TEXT,
    "sector_rank" INTEGER,
    "sector_momentum" TEXT,
    "composite_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "recommendation" TEXT,
    "rank" INTEGER,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from TEXT
);

-- Table: portfolio_transactions (0 rows)
CREATE TABLE IF NOT EXISTS "portfolio_transactions" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "date" TEXT NOT NULL  -- detected as TEXT from samples,
    "type" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "notes" TEXT,
    "created_at" TEXT NOT NULL DEFAULT NOW()  -- detected as TEXT from samples
);

-- Table: portfolio_values (1 rows)
CREATE TABLE IF NOT EXISTS "portfolio_values" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "value" DOUBLE PRECISION NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()  -- detected as TIMESTAMP from samples
);

-- Table: prediction_log (8 rows)
CREATE TABLE IF NOT EXISTS "prediction_log" (
    "log_date" TIMESTAMP  -- detected as TIMESTAMP from samples,
    "trade_date" TIMESTAMP  -- detected as TIMESTAMP from samples,
    "symbol" TEXT,
    "direction" TEXT,
    "quality_score" INTEGER,
    "ml_probability" DOUBLE PRECISION,
    "prediction" TEXT,
    "entry_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_entry" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_exit" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_return" NUMERIC(18,6)  -- price/financial — exact precision,
    "was_correct" DOUBLE PRECISION,
    "outcome_date" TEXT  -- unknown sqlite type — defaulted to TEXT,
    "notes" DOUBLE PRECISION
);

-- Table: prices (1,818,003 rows)
CREATE TABLE IF NOT EXISTS "prices" (
    "symbol" TEXT NOT NULL,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "close" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "volume" BIGINT  -- large value candidate,
    "high" NUMERIC(18,6)  -- price/financial — exact precision,
    "low" NUMERIC(18,6)  -- price/financial — exact precision,
    "open" NUMERIC(18,6)  -- price/financial — exact precision,
    PRIMARY KEY ("symbol", "date")
);

-- Table: prices_adjusted (1,818,003 rows)
CREATE TABLE IF NOT EXISTS "prices_adjusted" (
    "symbol" TEXT NOT NULL,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "close" NUMERIC(18,6)  -- price/financial — exact precision,
    "volume" BIGINT  -- large value candidate,
    "high" NUMERIC(18,6)  -- price/financial — exact precision,
    "low" NUMERIC(18,6)  -- price/financial — exact precision,
    "open" NUMERIC(18,6)  -- price/financial — exact precision,
    PRIMARY KEY ("symbol", "date")
);

-- Table: recovery_signals (35 rows)
CREATE TABLE IF NOT EXISTS "recovery_signals" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "as_of_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "sector" TEXT,
    "list_type" TEXT NOT NULL,
    "close" NUMERIC(18,6)  -- price/financial — exact precision,
    "drawdown_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "base_days" INTEGER,
    "base_range_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_ratio_today" NUMERIC(18,6)  -- price/financial — exact precision,
    "base_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "dist_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "avg_vol_m" DOUBLE PRECISION,
    "triggered_date" DATE  -- detected as DATE from samples,
    "fresh" BOOLEAN  -- sampled — only 0/1 values,
    "trigger_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "trigger_vol_x" DOUBLE PRECISION,
    "current_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "move_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "pre_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "kse_regime_ok" BOOLEAN  -- sampled — only 0/1 values,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from TEXT
);

-- Table: screened_dates (1,548 rows)
CREATE TABLE IF NOT EXISTS "screened_dates" (
    "date" DATE  -- detected as DATE from samples,
    PRIMARY KEY ("date")
);

-- Table: sector_signals (63,328 rows)
CREATE TABLE IF NOT EXISTS "sector_signals" (
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "sector" TEXT NOT NULL,
    "rs_score_20" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_score_50" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_rank" INTEGER,
    "rs_rank_prev" INTEGER,
    "breadth_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "adv_dec_ratio" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_ratio" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_inflection" INTEGER DEFAULT 0,
    "regime" TEXT,
    "composite_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "flow_smart_net_5d" NUMERIC(18,6)  -- price/financial — exact precision,
    "flow_smart_net_20d" NUMERIC(18,6)  -- price/financial — exact precision,
    "flow_retail_net_5d" NUMERIC(18,6)  -- price/financial — exact precision,
    "flow_retail_net_20d" NUMERIC(18,6)  -- price/financial — exact precision,
    "flow_direction" TEXT,
    "sector_ema50" DOUBLE PRECISION,
    "sector_above_ema" INTEGER,
    "sector_ema_slope" DOUBLE PRECISION,
    "sector_stage" TEXT,
    "sector_pivot_dist_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "sector_rs_new_high" INTEGER,
    PRIMARY KEY ("date", "sector")
);

-- Table: sectors (2,467 rows)
CREATE TABLE IF NOT EXISTS "sectors" (
    "symbol" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    PRIMARY KEY ("symbol")
);

-- Table: setup_log (205,678 rows)
CREATE TABLE IF NOT EXISTS "setup_log" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "symbol" TEXT NOT NULL,
    "setup_date" DATE NOT NULL  -- gate-verified YYYY-MM-DD, no anomalies,
    "setup_type" TEXT NOT NULL,
    "regime" TEXT,
    "rs_rank" INTEGER,
    "sector_rs_rank" INTEGER,
    "rank_change" INTEGER,
    "rs_score_20" NUMERIC(18,6)  -- price/financial — exact precision,
    "base_tightness" NUMERIC(18,6)  -- price/financial — exact precision,
    "vol_contraction" DOUBLE PRECISION,
    "pivot_distance_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "bos_flag" BOOLEAN  -- sampled — only 0/1 values,
    "sector" TEXT,
    "fwd_return_5d" NUMERIC(18,6)  -- price/financial — exact precision,
    "fwd_return_10d" NUMERIC(18,6)  -- price/financial — exact precision,
    "fwd_return_20d" NUMERIC(18,6)  -- price/financial — exact precision,
    "outcome_label" TEXT,
    "outcome_tagged_date" DATE  -- gate-verified YYYY-MM-DD, no anomalies,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from TEXT
);

-- Table: sim_portfolio_trades (4,160 rows)
CREATE TABLE IF NOT EXISTS "sim_portfolio_trades" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "setup_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "direction" TEXT DEFAULT 'LONG',
    "signal_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "entry_price" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "target_1r" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "trigger_date" DATE  -- detected as DATE from samples,
    "t1_hit" INTEGER DEFAULT 0,
    "exit_date" DATE  -- detected as DATE from samples,
    "exit_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "outcome" TEXT,
    "skip_reason" TEXT,
    "shares" DOUBLE PRECISION,
    "position_value" DOUBLE PRECISION,
    "capital_at_entry" NUMERIC(18,6)  -- price/financial — exact precision,
    "pl_pkr" NUMERIC(18,6)  -- price/financial — exact precision,
    "realized_r" DOUBLE PRECISION,
    "portfolio_after" DOUBLE PRECISION
);

-- Table: sim_portfolio_trades_v2 (4,160 rows)
CREATE TABLE IF NOT EXISTS "sim_portfolio_trades_v2" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "setup_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "direction" TEXT DEFAULT 'LONG',
    "quality_score" INTEGER,
    "signal_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "entry_price" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "target_1r" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "risk_frac" DOUBLE PRECISION,
    "trigger_date" DATE  -- detected as DATE from samples,
    "t1_hit" INTEGER DEFAULT 0,
    "exit_date" DATE  -- detected as DATE from samples,
    "exit_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "outcome" TEXT,
    "skip_reason" TEXT,
    "shares" DOUBLE PRECISION,
    "position_value" DOUBLE PRECISION,
    "capital_at_entry" NUMERIC(18,6)  -- price/financial — exact precision,
    "pl_pkr" NUMERIC(18,6)  -- price/financial — exact precision,
    "realized_r" DOUBLE PRECISION,
    "portfolio_after" DOUBLE PRECISION
);

-- Table: sim_portfolio_trades_v3 (4,160 rows)
CREATE TABLE IF NOT EXISTS "sim_portfolio_trades_v3" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "setup_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "direction" TEXT DEFAULT 'LONG',
    "signal_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "entry_price" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "regime_active" INTEGER DEFAULT 1,
    "trigger_date" DATE  -- detected as DATE from samples,
    "exit_date" DATE  -- detected as DATE from samples,
    "exit_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "outcome" TEXT,
    "skip_reason" TEXT,
    "shares" DOUBLE PRECISION,
    "position_value" DOUBLE PRECISION,
    "capital_at_entry" NUMERIC(18,6)  -- price/financial — exact precision,
    "pl_pkr" NUMERIC(18,6)  -- price/financial — exact precision,
    "realized_r" DOUBLE PRECISION,
    "portfolio_after" DOUBLE PRECISION
);

-- Table: stm_signals (1,718 rows)
CREATE TABLE IF NOT EXISTS "stm_signals" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "as_of_date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "sector" TEXT,
    "latest_close" NUMERIC(18,6)  -- price/financial — exact precision,
    "day_low" NUMERIC(18,6)  -- price/financial — exact precision,
    "ma21" DOUBLE PRECISION,
    "ma50" DOUBLE PRECISION,
    "avg_vol_10d" DOUBLE PRECISION,
    "range_5d_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "atr_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from TEXT
);

-- Table: stock_market_cap (314 rows)
CREATE TABLE IF NOT EXISTS "stock_market_cap" (
    "symbol" TEXT NOT NULL,
    "shares_m" DOUBLE PRECISION,
    "market_cap_m" DOUBLE PRECISION,
    "cap_date" DATE NOT NULL  -- detected as DATE from samples, hardcoded default removed,
    PRIMARY KEY ("symbol")
);

-- Table: stock_metadata (314 rows)
CREATE TABLE IF NOT EXISTS "stock_metadata" (
    "symbol" TEXT,
    "company_name" TEXT,
    "sector" TEXT,
    "listing_date" DATE  -- detected as DATE from samples,
    "delisting_date" DATE  -- detected as DATE from samples,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE  -- sampled — only 0/1 values,
    "in_kse100" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    PRIMARY KEY ("symbol")
);

-- Table: stock_signals (679,462 rows)
CREATE TABLE IF NOT EXISTS "stock_signals" (
    "date" DATE NOT NULL  -- detected as DATE from samples,
    "symbol" TEXT NOT NULL,
    "rs_score_20" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_score_50" NUMERIC(18,6)  -- price/financial — exact precision,
    "rs_rank" INTEGER,
    "rs_rank_prev" INTEGER,
    "rank_change" INTEGER,
    "sector_rs_rank" INTEGER,
    "base_tightness" NUMERIC(18,6)  -- price/financial — exact precision,
    "bos_flag" BOOLEAN  -- sampled — only 0/1 values,
    "vol_contraction" DOUBLE PRECISION,
    "avg_vol_10d" DOUBLE PRECISION,
    "pivot_high" NUMERIC(18,6)  -- price/financial — exact precision,
    "pivot_distance_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "stage2_bull" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    "close_above_ema50" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    "ema50_slope_pos" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    "base_duration" INTEGER,
    "overhead_clear" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    "near_pivot_days" INTEGER,
    "close_above_ema150" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    "ema150_slope_pos" BOOLEAN  -- fix6: gate-verified 0/1/NULL only,
    PRIMARY KEY ("date", "symbol")
);

-- Table: symbol_active_dates (1,116,924 rows)
CREATE TABLE IF NOT EXISTS "symbol_active_dates" (
    "symbol" TEXT NOT NULL,
    "date" DATE NOT NULL  -- detected as DATE from samples,
    PRIMARY KEY ("symbol", "date")
);

-- Table: trade_setups (673 rows)
CREATE TABLE IF NOT EXISTS "trade_setups" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "created_date" DATE NOT NULL  -- detected as DATE from samples,
    "direction" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "sector" TEXT NOT NULL,
    "sector_momentum" TEXT NOT NULL,
    "stock_perf_30d" DOUBLE PRECISION NOT NULL,
    "stock_perf_10d" DOUBLE PRECISION NOT NULL,
    "latest_close" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "support_level" DOUBLE PRECISION,
    "resistance_level" DOUBLE PRECISION,
    "entry_price" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "stop_loss" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "target_1r" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "target_2r" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "risk_pct" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "atr_pct" NUMERIC(18,6) NOT NULL  -- price/financial — exact precision,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "outcome" TEXT,
    "notes" TEXT,
    "quality_score" INTEGER DEFAULT 0,
    "quality_checks" TEXT DEFAULT '{}',
    "range_width_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "range_window" INTEGER,
    "sector_rank" INTEGER,
    "breadth_score" NUMERIC(18,6)  -- price/financial — exact precision,
    "source" TEXT DEFAULT 'System',
    "actual_exit" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_pl_pkr" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_pl_pct" NUMERIC(18,6)  -- price/financial — exact precision,
    "actual_rr" NUMERIC(18,6)  -- price/financial — exact precision,
    "holding_days" INTEGER,
    "exit_date" DATE  -- detected as DATE from samples,
    "actual_entry" NUMERIC(18,6)  -- price/financial — exact precision,
    "trade_execution" TEXT DEFAULT 'Paper',
    "regime_at_entry" TEXT,
    "days_since_last_transition" INTEGER,
    "days_to_nearest_transition" INTEGER
);

-- Table: uin_settlement (0 rows)
CREATE TABLE IF NOT EXISTS "uin_settlement" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "date" TEXT NOT NULL  -- detected as TEXT from samples,
    "symbol" TEXT NOT NULL,
    "sett_pct_volume" NUMERIC(18,6)  -- price/financial — exact precision,
    "sett_pct_value" NUMERIC(18,6)  -- price/financial — exact precision
);

-- Table: valuation_findings (0 rows)
CREATE TABLE IF NOT EXISTS "valuation_findings" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY  -- primary key identity,
    "ticker" TEXT NOT NULL,
    "research_date" TEXT NOT NULL  -- detected as TEXT from samples,
    "current_price" NUMERIC(18,6)  -- price/financial — exact precision,
    "dcf_value" DOUBLE PRECISION,
    "pe_value" NUMERIC(18,6)  -- price/financial — exact precision,
    "pb_value" DOUBLE PRECISION,
    "graham_value" DOUBLE PRECISION,
    "bear_value" DOUBLE PRECISION,
    "base_value" DOUBLE PRECISION,
    "bull_value" DOUBLE PRECISION,
    "conviction" INTEGER,
    "decision" TEXT,
    "thesis" TEXT,
    "assumptions" TEXT,
    "created_at" TIMESTAMP DEFAULT NOW()  -- fix5: upgraded from SQLite datetime('now')
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS "idx_chat_created"
    ON "agent_chat_log" ("created_at");

CREATE INDEX IF NOT EXISTS "idx_chat_session"
    ON "agent_chat_log" ("session_id");

CREATE INDEX IF NOT EXISTS "idx_agent_log_date"
    ON "agent_learning_log" ("run_date");

CREATE INDEX IF NOT EXISTS "idx_agent_opp_date"
    ON "agent_opportunities" ("run_date");

CREATE INDEX IF NOT EXISTS "idx_agent_opp_status"
    ON "agent_opportunities" ("status");

CREATE INDEX IF NOT EXISTS "idx_agent_opp_symbol"
    ON "agent_opportunities" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_ref_bo_symbol"
    ON "agent_reference_breakouts" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_agent_reports_date"
    ON "agent_reports" ("run_date");

CREATE INDEX IF NOT EXISTS "idx_bt_date"
    ON "backtest_setups" ("as_of_date");

CREATE INDEX IF NOT EXISTS "idx_bt_symbol"
    ON "backtest_setups" ("symbol");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_bt_unique"
    ON "backtest_setups" ("as_of_date", "symbol", "direction");

CREATE INDEX IF NOT EXISTS "idx_fs_ticker"
    ON "financial_snapshots" ("ticker");

CREATE INDEX IF NOT EXISTS "idx_idx_date"
    ON "index_prices" ("date");

CREATE INDEX IF NOT EXISTS "idx_mf_date"
    ON "market_flows" ("date");

CREATE INDEX IF NOT EXISTS "idx_mf_sector"
    ON "market_flows" ("sector");

CREATE INDEX IF NOT EXISTS "idx_mf_type"
    ON "market_flows" ("flow_type");

CREATE UNIQUE INDEX IF NOT EXISTS "uix_market_flows_key"
    ON "market_flows" ("date", "flow_type", "client_type", "sector", "market_type");

CREATE INDEX IF NOT EXISTS "idx_regime_date"
    ON "market_regime" ("date");

CREATE INDEX IF NOT EXISTS "idx_mv_date"
    ON "mv_signals" ("as_of_date");

CREATE INDEX IF NOT EXISTS "idx_mv_sym_date"
    ON "mv_signals" ("symbol", "as_of_date");

CREATE INDEX IF NOT EXISTS "idx_mv_type_date"
    ON "mv_signals" ("signal_type", "as_of_date");

CREATE INDEX IF NOT EXISTS "idx_port_date"
    ON "portfolio_signals" ("as_of_date");

CREATE INDEX IF NOT EXISTS "idx_port_score_date"
    ON "portfolio_signals" ("as_of_date", "composite_score");

CREATE INDEX IF NOT EXISTS "idx_portfolio_tx_date"
    ON "portfolio_transactions" ("date");

CREATE INDEX IF NOT EXISTS "idx_portfolio_val_date"
    ON "portfolio_values" ("date");

CREATE INDEX IF NOT EXISTS "idx_prices_date"
    ON "prices" ("date");

CREATE INDEX IF NOT EXISTS "idx_prices_sym_date"
    ON "prices" ("symbol", "date");

CREATE INDEX IF NOT EXISTS "idx_prices_symbol"
    ON "prices" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_pa_sym_date"
    ON "prices_adjusted" ("symbol", "date");

CREATE INDEX IF NOT EXISTS "idx_rec_date"
    ON "recovery_signals" ("as_of_date");

CREATE INDEX IF NOT EXISTS "idx_rec_type_date"
    ON "recovery_signals" ("list_type", "as_of_date");

CREATE INDEX IF NOT EXISTS "idx_sec_date_sector"
    ON "sector_signals" ("date", "sector");

CREATE INDEX IF NOT EXISTS "idx_sl_sym_date"
    ON "setup_log" ("symbol", "setup_date");

CREATE INDEX IF NOT EXISTS "idx_sim_date"
    ON "sim_portfolio_trades" ("setup_date");

CREATE INDEX IF NOT EXISTS "idx_sim_exit"
    ON "sim_portfolio_trades" ("exit_date");

CREATE INDEX IF NOT EXISTS "idx_sim_symbol"
    ON "sim_portfolio_trades" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_sim2_date"
    ON "sim_portfolio_trades_v2" ("setup_date");

CREATE INDEX IF NOT EXISTS "idx_sim2_exit"
    ON "sim_portfolio_trades_v2" ("exit_date");

CREATE INDEX IF NOT EXISTS "idx_sim2_symbol"
    ON "sim_portfolio_trades_v2" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_v3_date"
    ON "sim_portfolio_trades_v3" ("setup_date");

CREATE INDEX IF NOT EXISTS "idx_v3_symbol"
    ON "sim_portfolio_trades_v3" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_stm_date"
    ON "stm_signals" ("as_of_date");

CREATE INDEX IF NOT EXISTS "idx_stm_sym_date"
    ON "stm_signals" ("symbol", "as_of_date");

CREATE INDEX IF NOT EXISTS "idx_ss_sym_date"
    ON "stock_signals" ("symbol", "date");

CREATE INDEX IF NOT EXISTS "idx_sad_date"
    ON "symbol_active_dates" ("date");

CREATE INDEX IF NOT EXISTS "idx_sad_symbol"
    ON "symbol_active_dates" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_setups_status"
    ON "trade_setups" ("status");

CREATE INDEX IF NOT EXISTS "idx_setups_symbol"
    ON "trade_setups" ("symbol");

CREATE INDEX IF NOT EXISTS "idx_us_date"
    ON "uin_settlement" ("date");

CREATE INDEX IF NOT EXISTS "idx_us_symbol"
    ON "uin_settlement" ("symbol");
